version: "2.3"

services:
    postgres:
        container_name: service-postgres
        image: postgres:12
        environment: &db_env
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
          - 5432
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
        networks:
          - postgres

    jackbox-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        environment:
          <<: *db_env
          PREFIX: ${PREFIX:-~/.local}
          CCACHE_DIR: /jackbox/.ccache
          CORES_DIR: /cores
        volumes:
          - .:/jackbox:rw
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8080:8080
          - 8081:8081
        working_dir: /jackbox
        entrypoint:
          - ./tests/run_as_user.sh
        depends_on:
          - postgres
        networks:
          - postgres
          - dockerbridge

networks:
    postgres:
        driver: bridge
    dockerbridge:
        enable_ipv6: true
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "true"
        ipam:
            driver: default
            config:
             - subnet: 2001:3984:3989::/64
               gateway: 2001:3984:3989::1
